jenkins: fix first run missing default value for SAVE_RESULTING_NOTEBOOK_TIMEOUT
This happens only on the first run with the new config SAVE_RESULTING_NOTEBOOK_TIMEOUT.

Even if it's on the first run only, it will happen repeatedly each time
we have a new branch and we create a new matching "job" for the new
branch on Jenkins.  The first run of the new job will be missing the
default value for SAVE_RESULTING_NOTEBOOK_TIMEOUT.

It does not matter for other params where the default value is empty string
anyways.  But SAVE_RESULTING_NOTEBOOK_TIMEOUT requires an int so that's why it
matters.

Fix this kind of error during the `nbconvert` step:
```
  + jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout= --allow-errors --output-dir buildout --output eccc-geoapi-climate-stations.output.ipynb pavics-sdi-master/docs/source/notebooks/eccc-geoapi-climate-stations.ipynb
  Traceback (most recent call last):
    File "/opt/conda/envs/birdy/bin/jupyter-nbconvert", line 10, in <module>
      sys.exit(main())
               ^^^^^^
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/jupyter_core/application.py", line 283, in launch_instance
      super().launch_instance(argv=argv, **kwargs)
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/traitlets/config/application.py", line 1075, in launch_instance
      app.start()
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 420, in start
      self.convert_notebooks()
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 586, in convert_notebooks
      self.exporter = cls(config=self.config)
                      ^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 123, in __init__
      self._init_preprocessors()
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 290, in _init_preprocessors
      self.register_preprocessor(preprocessor)
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 254, in register_preprocessor
      return self.register_preprocessor(preprocessor_cls, enabled)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 267, in register_preprocessor
      self.register_preprocessor(preprocessor(parent=self), enabled)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/nbconvert/preprocessors/execute.py", line 48, in __init__
      Preprocessor.__init__(self, nb=nb, **kw)
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/nbconvert/preprocessors/base.py", line 42, in __init__
      super().__init__(**kw)
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/nbclient/client.py", line 452, in __init__
      super().__init__(**kw)
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/traitlets/config/configurable.py", line 116, in __init__
      self.config = config
      ^^^^^^^^^^^
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/traitlets/traitlets.py", line 716, in __set__
      self.set(obj, value)
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/traitlets/traitlets.py", line 706, in set
      obj._notify_trait(self.name, old_value, new_value)
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/traitlets/traitlets.py", line 1513, in _notify_trait
      self.notify_change(
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/traitlets/traitlets.py", line 1525, in notify_change
      return self._notify_observers(change)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/traitlets/traitlets.py", line 1568, in _notify_observers
      c(event)
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/traitlets/traitlets.py", line 1143, in compatible_observer
      return func(self, change)
             ^^^^^^^^^^^^^^^^^^
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/traitlets/config/configurable.py", line 232, in _config_changed
      self._load_config(change.new, traits=traits, section_names=section_names)
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/traitlets/config/configurable.py", line 193, in _load_config
      setattr(self, name, deepcopy(config_value))
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/traitlets/traitlets.py", line 716, in __set__
      self.set(obj, value)
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/traitlets/traitlets.py", line 690, in set
      new_value = self._validate(obj, value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/traitlets/traitlets.py", line 722, in _validate
      value = self.validate(obj, value)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/traitlets/traitlets.py", line 2637, in validate
      self.error(obj, value)
    File "/opt/conda/envs/birdy/lib/python3.11/site-packages/traitlets/traitlets.py", line 831, in error
      raise TraitError(e)
  traitlets.traitlets.TraitError: The 'timeout' trait of an ExecutePreprocessor instance expected an int, not the str ''.
```