runtest: add ability to regex replace "pavics" to "boreas" to force use testdata from prod
Add "TEST_USE_PROD_DATA" on any lines that we need to regex replace
"pavics" to "boreas".

For pavics-landing notebooks that use huge data from .ncml:
```
HTTPError: 404 Client Error:  for url: http://lvupavicsdev.ouranos.ca:8083/twitcher/ows/proxy/thredds/catalog/datasets/simulations/bias_adjusted/cmip5/ouranos/cb-oura-1.0/catalog.xml
```

Can not replicate all those .nc files that provides those .ncml.