docker: add libnetcdf-dev for ravenpy install
```
/opt/conda/envs/birdy/lib/python3.7/site-packages/pip/_internal/commands/install.py:230: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/envs/birdy/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qauah8hl/ravenpy_038ba83ba3ee4f2bb162c48649e94315/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qauah8hl/ravenpy_038ba83ba3ee4f2bb162c48649e94315/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__)
;code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9y_3nvj2/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/envs/birdy/include/python3.7m/ravenpy --with-binaries
         cwd: /tmp/pip-install-qauah8hl/ravenpy_038ba83ba3ee4f2bb162c48649e94315/
    Complete output (41 lines):
    running install
    Downloading raven source code..
    Extracting raven source code..
    Compiling raven..
    rm -f ./.depend
    g++ -Wno-deprecated -Dnetcdf                 -MM OrographicCorrections.cpp PotentialMelt.cpp Transformation.cpp Model.cpp GWStressPeriodClass.cpp GreenAmpt.cpp ForcingGrid.cpp CapillaryRise.cpp ParseFEWSRunInfo.cpp Advection.cpp SoilEvaporation.cpp OpenWaterEvap.cpp OverlapExchangeClass.cpp SoilClass.cpp LatFlush.cpp MassRouting.cpp
 Convolution.cpp StandardOutput.cpp UpdateForcings.cpp Assimilate.cpp SubBasin.cpp CustomOutput.cpp ParseEnsembleFile.cpp StateVariables.cpp VegetationClass.cpp ParseGWSWExchangeFile.cpp SnowMeltRefreeze.cpp SnowParams.cpp LateralExchangeABC.cpp SoilProfile.cpp EnergyTransport.cpp TimeSeries.cpp Sublimation.cpp Forcings.cpp HRUGroups.cpp Radiation.cpp VegetationParams.cpp TransientParam.cpp Evaporation.cpp ParseHRUFile.cpp ModelForcingGrids.cpp Infiltration.cpp GlobalParams.cpp ModelInitialize.cpp SparseMatrix.cpp SubbasinGroups.cpp ParseInput.cpp SurfaceEnergyExchange.cpp RavenMain.cpp LandUseClass.cpp ParseInitialConditionFile.cpp HydroUnits.cpp Gauge.cpp ProcessGro
up.cpp Solvers.cpp Interflow.cpp SnowTempEvolve.cpp SoilParams.cpp HydroProcessABC.cpp GWSolvers.cpp Recharge.cpp PartitionPrecip.cpp ParseLib.cpp GWGeometry.cpp Flush.cpp Baseflow.cpp ModelEnsemble.cpp Transport.cpp GlacierProcesses.cpp AquiferStack.cpp SnowBalance.cpp NetCDFReading.cpp ParseGWSWOverlapFile.cpp TimeSeriesABC.cpp VegetationMovers.cpp Decay.cpp ModelParamCheck.cpp ParseLiveFile.cpp IrregularTimeSeries.cpp DepressionProcesses.cpp SnowAlbedo.cpp UnitTesting.cpp PrairieSnow.cpp CommonFunctions.cpp Diagnostics.cpp ParseGWPropsFile.cpp ChannelXSect.cpp CropGrowth.cpp GroundwaterModel.cpp ParseTimeSeriesFile.cpp TerrainClass.cpp Abstraction.cpp Reservoir.cpp
 Percolation.cpp Drain.cpp UTM_to_LatLong.cpp ParsePropertyFile.cpp ParseGWGeometryFile.cpp LatAdvection.cpp HeatConduction.cpp>>./.depend;
    g++ -Wno-deprecated -Dnetcdf                   -c -o OrographicCorrections.o OrographicCorrections.cpp
    In file included from Model.h:8,
                     from OrographicCorrections.cpp:5:
    RavenInclude.h:21:10: fatal error: netcdf.h: No such file or directory
     #include <netcdf.h>
              ^~~~~~~~~~
    compilation terminated.
    make: *** [<builtin>: OrographicCorrections.o] Error 1
```