stress-tests.ipynb: fix not showing helpful error in Jenkins
Before this fix, this is what Jenkins shows, not very helpful:
```
  _____________________ notebooks/stress-tests.ipynb::Cell 2 _____________________
  Notebook cell execution failed
  Cell 2: Cell execution caused an exception

  Input:
  # NBVAL_IGNORE_OUTPUT

  test_statuses = []
  for bird in TEST_WPS_BIRDS:
      bird_url = f"{TWITCHER_URL}/{bird}/wps?service=wps&request=getcapabilities"
      expect_status_code = 200
      results = stress_test_requests(bird_url, runs=TEST_RUNS, code=expect_status_code,
                                     max_err_code=TEST_MAX_ERR_CODE, max_avg_time=TEST_MAX_AVG_TIME,
                                     abort_retries=TEST_TIMEOUT_RETRY, abort_timeout=TEST_TIMEOUT_ABORT)
      test_statuses.append(results.status)
      print(results)
  failed_tests = sum(test_statuses)
  assert not failed_tests, f"Failed {failed_tests} tests."

  print("\nAll tests passed!")

  Traceback:

  ---------------------------------------------------------------------------
  AssertionError                            Traceback (most recent call last)
  <ipython-input-3-954e90dc833f> in <module>
       12     print(results)
       13 failed_tests = sum(test_statuses)
  ---> 14 assert not failed_tests, f"Failed {failed_tests} tests."
       15
       16 print("\nAll tests passed!")

  AssertionError: Failed -2 tests.
```

After this fix:
```
  _____________________ notebooks/stress-tests.ipynb::Cell 2 _____________________
  Notebook cell execution failed
  Cell 2: Cell execution caused an exception

  Input:
  # NBVAL_IGNORE_OUTPUT

  test_statuses = []
  failed_results = ''
  for bird in TEST_WPS_BIRDS:
      bird_url = f"{TWITCHER_URL}/{bird}/wps?service=wps&request=getcapabilities"
      expect_status_code = 200
      results = stress_test_requests(bird_url, runs=TEST_RUNS, code=expect_status_code,
                                     max_err_code=TEST_MAX_ERR_CODE, max_avg_time=TEST_MAX_AVG_TIME,
                                     abort_retries=TEST_TIMEOUT_RETRY, abort_timeout=TEST_TIMEOUT_ABORT)
      test_statuses.append(results.status)
      print(results)
      if results.status:
          failed_results = f"{failed_results}\n{results}"
  failed_tests = sum(test_statuses)
  assert not failed_tests, f"Failed {failed_tests} tests.  Failed results: {failed_results}"

  print("\nAll tests passed!")

  Traceback:

  ---------------------------------------------------------------------------
  AssertionError                            Traceback (most recent call last)
  <ipython-input-3-63ac944aa8d7> in <module>
       15         failed_results = f"{failed_results}\n{results}"
       16 failed_tests = sum(test_statuses)
  ---> 17 assert not failed_tests, f"Failed {failed_tests} tests.  Failed results: {failed_results}"
       18
       19 print("\nAll tests passed!")

  AssertionError: Failed -2 tests.  Failed results:
  Stress Test:
      Test:
          code: 200
          runs: 100
          max-avg-time:  1s
          max-err-code:  0
          sum-err-code:  4
          timeout-abort: 0s
          timeout-retry: 0
          timeout-count: 0
      Request:
          method: GET
          url:    https://pavics.ouranos.ca/twitcher/ows/proxy/finch/wps?service=wps&request=getcapabilities
          args:   {}
      Times:
          min: 0.028s
          avg: 0.235s
          max: 0.565s
      Results:
          Run     Codes     Delta     Times
            1       200    0.000s    0.189s
            2       200    0.021s    0.167s
            3       200    0.083s    0.406s
            4       200    0.010s    0.185s
            5       200    0.028s    0.186s
            6       200    0.022s    0.228s
            7       200    0.082s    0.373s
            8       200    0.070s    0.230s
            9       200    0.078s    0.277s
           10       200    0.018s    0.180s
           11       200    0.084s    0.230s
           12       200    0.048s    0.395s
           13       200    0.004s    0.227s
           14       200    0.002s    0.219s
           15       200    0.034s    0.341s
           16       200    0.065s    0.222s
           17       200    0.015s    0.231s
           18   (!) 401    0.071s    0.056s
           19       200    0.016s    0.199s
           20       200    0.090s    0.331s
           21       200    0.067s    0.219s
           22       200    0.089s    0.255s
           23       200    0.054s    0.184s
           24       200    0.023s    0.207s
           25       200    0.055s    0.328s
           26       200    0.079s    0.219s
           27       200    0.045s    0.289s
           28       200    0.045s    0.374s
           29       200    0.087s    0.565s
           30       200    0.026s    0.184s
           31   (!) 500    0.087s    0.028s
           32       200    0.089s    0.211s
           33       200    0.021s    0.365s
           34       200    0.078s    0.215s
           35       200    0.036s    0.222s
           36       200    0.040s    0.182s
           37       200    0.053s    0.232s
           38       200    0.063s    0.324s
           39       200    0.031s    0.171s
           40       200    0.037s    0.346s
           41       200    0.041s    0.182s
           42       200    0.043s    0.196s
           43       200    0.066s    0.332s
           44       200    0.098s    0.224s
           45       200    0.023s    0.187s
           46       200    0.072s    0.173s
           47       200    0.080s    0.200s
           48       200    0.042s    0.296s
           49       200    0.027s    0.320s
           50       200    0.030s    0.203s
           51       200    0.019s    0.177s
           52       200    0.056s    0.203s
           53       200    0.054s    0.303s
           54       200    0.063s    0.195s
           55       200    0.021s    0.185s
           56       200    0.072s    0.162s
           57       200    0.097s    0.199s
           58       200    0.062s    0.360s
           59       200    0.083s    0.224s
           60       200    0.025s    0.194s
           61       200    0.058s    0.397s
           62       200    0.091s    0.194s
           63       200    0.075s    0.189s
           64       200    0.002s    0.204s
           65       200    0.010s    0.298s
           66       200    0.049s    0.187s
           67       200    0.072s    0.193s
           68       200    0.018s    0.220s
           69       200    0.049s    0.241s
           70       200    0.050s    0.309s
           71       200    0.063s    0.221s
           72       200    0.064s    0.205s
           73       200    0.021s    0.383s
           74       200    0.024s    0.216s
           75       200    0.098s    0.178s
           76       200    0.012s    0.198s
           77       200    0.001s    0.321s
           78       200    0.039s    0.195s
           79       200    0.018s    0.207s
           80       200    0.048s    0.201s
           81       200    0.078s    0.211s
           82       200    0.100s    0.313s
           83       200    0.039s    0.216s
           84       200    0.076s    0.214s
           85       200    0.006s    0.304s
           86       200    0.077s    0.181s
           87       200    0.046s    0.205s
           88       200    0.047s    0.160s
           89       200    0.044s    0.321s
           90       200    0.052s    0.184s
           91       200    0.035s    0.217s
           92       200    0.074s    0.163s
           93       200    0.015s    0.169s
           94   (!) 500    0.045s    0.033s
           95       200    0.024s    0.307s
           96       200    0.067s    0.240s
           97       200    0.093s    0.241s
           98       200    0.087s    0.314s
           99   (!) 500    0.065s    0.030s
          100       200    0.062s    0.185s
      Summary:
          Detected 4 erroneous HTTP codes not equal to expected 200.
          Test failed.
  Stress Test:
      Test:
          code: 200
          runs: 100
          max-avg-time:  1s
          max-err-code:  0
          sum-err-code:  6
          timeout-abort: 0s
          timeout-retry: 0
          timeout-count: 0
      Request:
          method: GET
          url:    https://pavics.ouranos.ca/twitcher/ows/proxy/flyingpigeon/wps?service=wps&request=getcapabilities
          args:   {}
      Times:
          min: 0.030s
          avg: 0.137s
          max: 0.212s
      Results:
          Run     Codes     Delta     Times
            1       200    0.000s    0.150s
            2       200    0.012s    0.147s
            3       200    0.057s    0.137s
            4       200    0.086s    0.167s
            5       200    0.077s    0.140s
            6       200    0.023s    0.130s
            7       200    0.061s    0.130s
            8       200    0.083s    0.143s
            9       200    0.065s    0.160s
           10       200    0.087s    0.145s
           11       200    0.098s    0.153s
           12       200    0.081s    0.146s
           13       200    0.024s    0.158s
           14       200    0.028s    0.124s
           15       200    0.041s    0.148s
           16       200    0.045s    0.144s
           17       200    0.001s    0.181s
           18       200    0.012s    0.149s
           19   (!) 500    0.084s    0.037s
           20       200    0.078s    0.156s
           21       200    0.059s    0.150s
           22       200    0.091s    0.149s
           23       200    0.075s    0.144s
           24       200    0.036s    0.133s
           25       200    0.025s    0.128s
           26       200    0.020s    0.135s
           27       200    0.016s    0.156s
           28       200    0.016s    0.148s
           29       200    0.034s    0.131s
           30       200    0.078s    0.147s
           31       200    0.025s    0.143s
           32       200    0.043s    0.152s
           33       200    0.026s    0.155s
           34       200    0.092s    0.138s
           35       200    0.047s    0.151s
           36       200    0.035s    0.212s
           37       200    0.049s    0.158s
           38       200    0.041s    0.149s
           39       200    0.063s    0.151s
           40   (!) 500    0.060s    0.031s
           41       200    0.003s    0.142s
           42       200    0.014s    0.148s
           43       200    0.058s    0.153s
           44       200    0.004s    0.141s
           45       200    0.062s    0.140s
           46       200    0.024s    0.129s
           47       200    0.099s    0.126s
           48       200    0.086s    0.141s
           49       200    0.095s    0.128s
           50       200    0.039s    0.138s
           51       200    0.100s    0.156s
           52       200    0.091s    0.146s
           53       200    0.012s    0.130s
           54       200    0.029s    0.129s
           55       200    0.091s    0.148s
           56       200    0.027s    0.134s
           57       200    0.072s    0.133s
           58       200    0.083s    0.153s
           59       200    0.090s    0.140s
           60       200    0.053s    0.152s
           61       200    0.055s    0.146s
           62       200    0.067s    0.123s
           63       200    0.056s    0.138s
           64       200    0.031s    0.156s
           65       200    0.012s    0.138s
           66       200    0.013s    0.136s
           67       200    0.069s    0.116s
           68       200    0.082s    0.122s
           69       200    0.008s    0.133s
           70   (!) 500    0.024s    0.032s
           71       200    0.018s    0.169s
           72       200    0.008s    0.151s
           73       200    0.042s    0.102s
           74   (!) 500    0.052s    0.039s
           75       200    0.091s    0.145s
           76       200    0.090s    0.116s
           77       200    0.078s    0.125s
           78       200    0.042s    0.143s
           79   (!) 500    0.082s    0.030s
           80       200    0.030s    0.149s
           81       200    0.084s    0.149s
           82       200    0.064s    0.147s
           83       200    0.013s    0.164s
           84       200    0.081s    0.161s
           85   (!) 500    0.096s    0.040s
           86       200    0.036s    0.184s
           87       200    0.021s    0.148s
           88       200    0.012s    0.129s
           89       200    0.044s    0.136s
           90       200    0.065s    0.146s
           91       200    0.037s    0.112s
           92       200    0.019s    0.126s
           93       200    0.083s    0.139s
           94       200    0.041s    0.128s
           95       200    0.095s    0.113s
           96       200    0.058s    0.149s
           97       200    0.045s    0.177s
           98       200    0.069s    0.130s
           99       200    0.013s    0.125s
          100       200    0.004s    0.136s
      Summary:
          Detected 6 erroneous HTTP codes not equal to expected 200.
          Test failed.
```