docker: py311-250109: initial jenkins build, raven nbs, 3 nbs failure due to 2 errors
```
  ____ RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 3 ____
  Notebook cell execution failed
  Cell 3: Cell execution caused an exception

  Input:
  # We will add a wrapper to ensure that the following operations will preserve the original data attributes, such as units and variable names.
  with xr.set_options(keep_attrs=True):
      ERA5_reference = subset.subset_shape(
          ds.sel(time=slice(reference_start_day, reference_stop_day)), basin_contour
      )
      ERA5_tas = ERA5_reference["t2m"].resample(time="1D")
      ERA5_tmin = ERA5_tas.min().chunk(-1, -1, -1)
      ERA5_tmax = ERA5_tas.max().chunk(-1, -1, -1)
      ERA5_pr = ERA5_reference["tp"].resample(time="1D").sum().chunk(-1, -1, -1)

  ERA5_pr

  Traceback:

  ---------------------------------------------------------------------------
  TypeError                                 Traceback (most recent call last)
  Cell In[1], line 7
        3 ERA5_reference = subset.subset_shape(
        4     ds.sel(time=slice(reference_start_day, reference_stop_day)), basin_contour
        5 )
        6 ERA5_tas = ERA5_reference["t2m"].resample(time="1D")
  ----> 7 ERA5_tmin = ERA5_tas.min().chunk(-1, -1, -1)
        8 ERA5_tmax = ERA5_tas.max().chunk(-1, -1, -1)
        9 ERA5_pr = ERA5_reference["tp"].resample(time="1D").sum().chunk(-1, -1, -1)

  TypeError: DataArray.chunk() takes from 1 to 2 positional arguments but 4 were given

  _ RavenPy-master/docs/notebooks/08_Getting_and_bias_correcting_CMIP6_data.ipynb::Cell 7 _

  File /opt/conda/envs/birdy/lib/python3.11/site-packages/zarr/storage/_common.py:316, in make_store_path(store_like, path, mode, storage_options)
      314     else:
      315         msg = f"Unsupported type for store_like: '{type(store_like).__name__}'"  # type: ignore[unreachable]
  --> 316         raise TypeError(msg)
      318     result = await StorePath.open(store, path=path_normalized, mode=mode)
      320 if storage_options and not used_storage_options:

  TypeError: Unsupported type for store_like: 'FSMap'

  _ RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 11 _

  File /opt/conda/envs/birdy/lib/python3.11/site-packages/zarr/storage/_common.py:316, in make_store_path(store_like, path, mode, storage_options)
      314     else:
      315         msg = f"Unsupported type for store_like: '{type(store_like).__name__}'"  # type: ignore[unreachable]
  --> 316         raise TypeError(msg)
      318     result = await StorePath.open(store, path=path_normalized, mode=mode)
      320 if storage_options and not used_storage_options:

  TypeError: Unsupported type for store_like: 'FSMap'
```