docker: py311-241219: initial jenkins build, raven nbs, several errors, same cause
ImportError: cannot import name 'readers' from 'intake' (/opt/conda/envs/birdy/lib/python3.11/site-packages/intake/__init__.py)

17:12:24  =========================== short test summary info ============================
17:12:24  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 2
17:12:24  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 3
17:12:24  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 4
17:12:24  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 5
17:12:24  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 6
17:12:24  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 7
17:12:24  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 8
17:12:24  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 9
17:12:24  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 10
17:12:24  FAILED RavenPy-master/docs/notebooks/08_Getting_and_bias_correcting_CMIP6_data.ipynb::Cell 10
17:12:24  FAILED RavenPy-master/docs/notebooks/08_Getting_and_bias_correcting_CMIP6_data.ipynb::Cell 11
17:12:24  FAILED RavenPy-master/docs/notebooks/08_Getting_and_bias_correcting_CMIP6_data.ipynb::Cell 12
17:12:24  FAILED RavenPy-master/docs/notebooks/08_Getting_and_bias_correcting_CMIP6_data.ipynb::Cell 13
17:12:24  FAILED RavenPy-master/docs/notebooks/08_Getting_and_bias_correcting_CMIP6_data.ipynb::Cell 14
17:12:24  FAILED RavenPy-master/docs/notebooks/08_Getting_and_bias_correcting_CMIP6_data.ipynb::Cell 15
17:12:24  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 7
17:12:24  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 8
17:12:24  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 9
17:12:24  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 10
17:12:24  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 13
17:12:24  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 14
17:12:24  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 15
17:12:24  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 16
17:12:24  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 17
17:12:24  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 18
17:12:24  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 19
17:12:24  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 20
17:12:24  ================== 31 failed, 211 passed in 562.78s (0:09:22) ==================