docker: pin intake-esm since newer version activated validation of optional fields and broke our notebooks
According to @aulemahal (Pascal) optional fields should not have been
validated.  Pinning is just a stop gap solution to be able to release
the Jupyter env without breaking our notebooks.  We still need to find
solution to this problem.

```
ValidationError: 1 validation error for ESMCatalogModel
aggregation_control
  field required (type=value_error.missing)
```