docker: no need to jupyter labextension install @jupyter-widgets/jupyterlab-manager with jupyterlab v3
Build error:
```
Node v15.14.0

Yarn configuration loaded.
> /opt/conda/envs/birdy/bin/npm pack @jupyter-widgets/jupyterlab-manager
npm notice
npm notice 📦  @jupyter-widgets/jupyterlab-manager@3.0.1
npm notice === Tarball Contents ===
npm notice 14.5kB LICENSE
npm notice 2.8kB  README.md
npm notice 277B   lib/index.d.ts
npm notice 380B   lib/index.js
npm notice 5.9kB  lib/manager.d.ts
npm notice 15.3kB lib/manager.js
npm notice 1.9kB  lib/output.d.ts
npm notice 5.3kB  lib/output.js
npm notice 828B   lib/plugin.d.ts
npm notice 7.9kB  lib/plugin.js
npm notice 960B   lib/renderer.d.ts
npm notice 3.3kB  lib/renderer.js
npm notice 216B   lib/semvercache.d.ts
npm notice 862B   lib/semvercache.js
npm notice 3.3kB  package.json
npm notice 375B   schema/plugin.json
npm notice === Tarball Details ===
npm notice name:          @jupyter-widgets/jupyterlab-manager
npm notice version:       3.0.1
npm notice filename:      @jupyter-widgets/jupyterlab-manager-3.0.1.tgz
npm notice package size:  15.6 kB
npm notice unpacked size: 64.0 kB
npm notice shasum:        ba70c14282fb8bd3c6560588f4c7b90b2b2b05fb
npm notice integrity:     sha512-yhmakhiAFtKtZ[...]RptG4BvNdS+HA==
npm notice total files:   16
npm notice
jupyter-widgets-jupyterlab-manager-3.0.1.tgz
npm notice
npm notice New major version of npm available! 7.7.6 -> 8.3.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.3.0>
npm notice Run `npm install -g npm@8.3.0` to update!
npm notice

Node v15.14.0

Yarn configuration loaded.
Building jupyterlab assets (production, minimized)
> node /opt/conda/envs/birdy/lib/python3.9/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning @blueprintjs/core@3.52.0: Invalid bin entry for "upgrade-blueprint-2.0.0-rename" (in "@blueprintjs/core").
warning @blueprintjs/core@3.52.0: Invalid bin entry for "upgrade-blueprint-3.0.0-rename" (in "@blueprintjs/core").
error @npmcli/fs@1.1.0: The engine "node" is incompatible with this module. Expected version "^12.13.0 || ^14.15.0 || >=16". Got "15.14.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

npm dependencies failed to install
Traceback (most recent call last):

  File "/opt/conda/envs/birdy/lib/python3.9/site-packages/jupyterlab/debuglog.py", line 48, in debug_logging
    yield

  File "/opt/conda/envs/birdy/lib/python3.9/site-packages/jupyterlab/labextensions.py", line 140, in start
    build(clean_staging=self.should_clean,

  File "/opt/conda/envs/birdy/lib/python3.9/site-packages/jupyterlab/commands.py", line 482, in build
    return handler.build(name=name, version=version, static_url=static_url,

  File "/opt/conda/envs/birdy/lib/python3.9/site-packages/jupyterlab/commands.py", line 688, in build
    raise RuntimeError(msg)

RuntimeError: npm dependencies failed to install

Exiting application: lab
```