docker: fix conda install cli permission error
Fix for this error:
```
! conda install -c pyviz/label/dev jupyter-panel-proxy

Collecting package metadata (current_repodata.json): failed

NotWritableError: The current user does not have write permissions to a
required path.
  path: /opt/conda/pkgs/cache/37adb69c.json
  uid: 1000
  gid: 1000

If you feel that permissions on this path are set incorrectly, you can
manually
change them by executing

  $ sudo chown 1000:1000 /opt/conda/pkgs/cache/37adb69c.json

In general, it's not advisable to use 'sudo conda'.
```