docker: py311-241205: initial jenkins build, default nb, PAVICStutorial_Hydrology-02_Calibration.ipynb
```
  _ PAVICS-landing-master/content/notebooks/hydrology/PAVICStutorial_Hydrology-02_Calibration.ipynb::Cell 2 _
  Notebook cell execution failed
  Cell 2: Cell execution caused an exception

  Input:
  # In order to calibrate your model, you need to give the lower and higher bounds of the model. In this case, we are passing
  # the boundaries for a GR4JCN, but it's important to change them, if you are using another model.
  low_params = (0.01, -15.0, 10.0, 0.0, 1.0, 0.0)
  high_params = (2.5, 10.0, 700.0, 7.0, 30.0, 1.0)

  # Create SpotSetup instance to connect SPOTPY to our Raven emulator.
  spot_setup = SpotSetup(
      config=model_config,
      low=low_params,
      high=high_params,
  )

  Traceback:

  ---------------------------------------------------------------------------
  ValueError                                Traceback (most recent call last)
  Cell In[1], line 7
        4 high_params = (2.5, 10.0, 700.0, 7.0, 30.0, 1.0)
        6 # Create SpotSetup instance to connect SPOTPY to our Raven emulator.
  ----> 7 spot_setup = SpotSetup(
        8     config=model_config,
        9     low=low_params,
       10     high=high_params,
       11 )

  File /opt/conda/envs/birdy/lib/python3.11/site-packages/ravenpy/utilities/calibration.py:38, in SpotSetup.__init__(self, config, low, high, workdir)
       24 """Class to configure spotpy with Raven emulators.
       25
       26 Parameters
     (...)
       35     Work directory. If None, a temporary directory will be created.
       36 """
       37 if not config.is_symbolic:
  ---> 38     raise ValueError(
       39         "config should be a symbolic configuration, where params are not set to their numerical "
       40         "values."
       41     )
       43 self.config = config
       44 self.path = Path(workdir or tempfile.mkdtemp())

  ValueError: config should be a symbolic configuration, where params are not set to their numerical values.
```