docker: py311-250107: initial jenkins build, raven nbs, one error 03_Extracting_forcing_data.ipynb
```
  ____ RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 3 ____
  Notebook cell execution failed
  Cell 3: Cell execution caused an exception

  Input:
  # We will add a wrapper to ensure that the following operations will preserve the original data attributes, such as units and variable names.
  with xr.set_options(keep_attrs=True):
      ERA5_reference = subset.subset_shape(
          ds.sel(time=slice(reference_start_day, reference_stop_day)), basin_contour
      )
      ERA5_tas = ERA5_reference["t2m"].resample(time="1D")
      ERA5_tmin = ERA5_tas.min().chunk(-1, -1, -1)
      ERA5_tmax = ERA5_tas.max().chunk(-1, -1, -1)
      ERA5_pr = ERA5_reference["tp"].resample(time="1D").sum().chunk(-1, -1, -1)

  ERA5_pr

  Traceback:

  ---------------------------------------------------------------------------
  TypeError                                 Traceback (most recent call last)
  Cell In[1], line 7
        3 ERA5_reference = subset.subset_shape(
        4     ds.sel(time=slice(reference_start_day, reference_stop_day)), basin_contour
        5 )
        6 ERA5_tas = ERA5_reference["t2m"].resample(time="1D")
  ----> 7 ERA5_tmin = ERA5_tas.min().chunk(-1, -1, -1)
        8 ERA5_tmax = ERA5_tas.max().chunk(-1, -1, -1)
        9 ERA5_pr = ERA5_reference["tp"].resample(time="1D").sum().chunk(-1, -1, -1)

  TypeError: DataArray.chunk() takes from 1 to 2 positional arguments but 4 were given
```