stress-test.ipynb: fix incorrect calculation of number of failed tests
Below is the result from a nightly run on production.  It found 4 failed tests
but in fact none were failing since failed_results was empty.

```
  =================================== FAILURES ===================================
  _____________________ notebooks/stress-tests.ipynb::Cell 2 _____________________
  Notebook cell execution failed
  Cell 2: Cell execution caused an exception

  Input:
  # NBVAL_IGNORE_OUTPUT

  test_statuses = []
  failed_results = ''
  for bird in TEST_WPS_BIRDS:
      bird_url = f"{TWITCHER_URL}/{bird}/wps?service=wps&request=getcapabilities"
      expect_status_code = 200
      results = stress_test_requests(bird_url, runs=TEST_RUNS, code=expect_status_code,
                                     max_err_code=TEST_MAX_ERR_CODE, max_avg_time=TEST_MAX_AVG_TIME,
                                     abort_retries=TEST_TIMEOUT_RETRY, abort_timeout=TEST_TIMEOUT_ABORT)
      test_statuses.append(results.status)
      print(results)
      if results.status:
          failed_results = f"{failed_results}\n{results}"
  failed_tests = len([status != 0 for status in test_statuses])
  assert not failed_tests, f"Failed {failed_tests} tests.  Failed results: {failed_results}"

  print("\nAll tests passed!")

  Traceback:

  ---------------------------------------------------------------------------
  AssertionError                            Traceback (most recent call last)
  <ipython-input-3-de267d95df0f> in <module>
       15         failed_results = f"{failed_results}\n{results}"
       16 failed_tests = len([status != 0 for status in test_statuses])
  ---> 17 assert not failed_tests, f"Failed {failed_tests} tests.  Failed results: {failed_results}"
       18
       19 print("\nAll tests passed!")

  AssertionError: Failed 4 tests.  Failed results:

  =========================== short test summary info ============================
  FAILED notebooks/stress-tests.ipynb::Cell 2
  ============= 1 failed, 174 passed, 1 skipped in 428.88s (0:07:08) =============
```