docker: try bokeh from pip since pinning old jupyterlab do not work
Because the latest bokeh from conda do not work with latest jupyterlab,
hopefully the latest bokeh from pip will do.

Step 9/18 : RUN jupyter lab build
 ---> Running in 5ba0df183f0c
[LabBuildApp] JupyterLab 1.2.5
[LabBuildApp] Building in /usr/local/envs/birdy/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
Removing intermediate container 5ba0df183f0c
 ---> 69a1687d3685
Step 10/18 : RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager     && jupyter serverextension enable voila --sys-prefix     &&
jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-leaflet     && jupyter labextension install @bokeh/jupyter_bokeh
 ---> Running in 1d52d8496904
Building jupyterlab assets (build:prod:minimize)
-
An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details:  /tmp/jupyterlab-debug-vv71qp2f.log
The command '/bin/sh -c jupyter labextension install @jupyter-widgets/jupyterlab-manager     && jupyter serverextension enable voila --sys-prefix
    && jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-leaflet     && jupyter labextension install @bokeh/jupyter_bokeh'
returned a non-zero code: 1