docker: remove jupyterlab-clipboard since not installing
https://github.com/Bamieh/jupyterlab-clipboard

```
Node v13.13.0

Yarn configuration loaded.
> /opt/conda/envs/birdy/bin/npm pack jupyterlab-clipboard
npm notice
npm notice 📦  jupyterlab-clipboard@0.3.0-alpha
npm notice === Tarball Contents ===
npm notice 670B  lib/clipboard.js
npm notice 2.3kB lib/dialogs.js
npm notice 6.0kB lib/image-editor.js
npm notice 5.3kB lib/index.js
npm notice 1.3kB package.json
npm notice 1.2kB README.md
npm notice 93B   lib/clipboard.d.ts
npm notice 232B  lib/dialogs.d.ts
npm notice 487B  lib/image-editor.d.ts
npm notice 129B  lib/index.d.ts
npm notice === Tarball Details ===
npm notice name:          jupyterlab-clipboard
npm notice version:       0.3.0-alpha
npm notice filename:      jupyterlab-clipboard-0.3.0-alpha.tgz
npm notice package size:  5.0 kB
npm notice unpacked size: 17.7 kB
npm notice shasum:        cc0df959ab42c2b8244fcf8469ebeecb0fc1ce92
npm notice integrity:     sha512-88dVN6QCsmW2R[...]RcG6Yr+cCYCLQ==
npm notice total files:   10
npm notice
jupyterlab-clipboard-0.3.0-alpha.tgz

Fetching URL: https://registry.yarnpkg.com/jupyterlab-clipboard
Fetching URL: https://registry.yarnpkg.com/jupyterlab-clipboard
Traceback (most recent call last):

  File "/opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 93, in start
    ans = self.run_task()

  File "/opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 149, in run_task
    for i, arg in enumerate(self.extra_args)

  File "/opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 149, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "/opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/commands.py", line 388, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/commands.py", line 603, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "/opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/commands.py", line 1550, in _install_extension
    raise ValueError(msg)

ValueError: The extension "jupyterlab-clipboard" does not yet support the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.1.2 <2.2.0          >=0.19.1 <0.20.0@jupyterlab/application
>=4.1.0 <4.2.0          >=2.2.1 <3.0.0 @jupyterlab/coreutils
>=2.1.2 <2.2.0          >=0.19.3 <0.20.0@jupyterlab/filebrowser
>=2.1.2 <2.2.0          >=0.19.2 <0.20.0@jupyterlab/notebook
>=5.1.0 <5.2.0          >=3.2.1 <4.0.0 @jupyterlab/services

Exiting application: jupyter
```