docker: py311-241021: initial jenkins build, default nb, 3 nb failure, 2 root cause, lots of output change
KeyError: 'heating_degree_days'
pavics-sdi-fix-pjei-11/docs/source/notebooks/forecasts.ipynb

ImportError: cannot import name 'convert_calendar' from
'xclim.core.calendar'
(/opt/conda/envs/birdy/lib/python3.11/site-packages/xclim/core/calendar.py)

PAVICS-landing-fix-pjei-11/content/notebooks/climate_indicators/PAVICStutorial_ClimateDataAnalysis-5Visualization.ipynb::Cell
0
PAVICS-landing-fix-pjei-11/content/notebooks/climate_indicators/PAVICStutorial_ClimateDataAnalysis-6Regridding_Conversion.ipynb::Cell
0

The rest of the errors are not code errors but output change so a simple
refresh will be able to fix.