docker: pin latest jupyterlab v2 because v3 is breaking our jupyterlab extensions
```
Step 10/19 : RUN jupyter lab build
 ---> Running in 224b7b9a7d1e
[LabBuildApp] JupyterLab 3.0.6
[LabBuildApp] Building in /opt/conda/envs/birdy/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] WARNING | The extension "@mamba-org/gator-lab" is outdated.

[LabBuildApp] WARNING | The extension "@jupyterlab/git" is outdated.

[LabBuildApp] WARNING | The extension "nbdime-jupyterlab" is outdated.

Removing intermediate container 224b7b9a7d1e
 ---> 0cff8bc458f9
Step 11/19 : RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager     && jupyter serverextension enable voila --sys-prefix     && jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-leaflet     && jupyter labextension install @bokeh/jupyter_bokeh     && jupyter labextension install @pyviz/jupyterlab_pyviz     && jupyter labextension install @jupyterlab/debugger     && jupyter labextension install @jupyterlab/google-drive     && jupyter labextension install jupyterlab-topbar-extension                                     jupyterlab-system-monitor                                     jupyterlab-topbar-text
       jupyterlab-logout                                     jupyterlab-theme-toggle                                     jupyterlab_conda
 ---> Running in 5c8c3a2566fa
Building jupyterlab assets (production, minimized)
The extension "@mamba-org/gator-lab" is outdated.

The extension "@jupyterlab/git" is outdated.

The extension "nbdime-jupyterlab" is outdated.

Enabling: voila
- Writing config: /opt/conda/envs/birdy/etc/jupyter
    - Validating...
      voila 0.2.6 OK
Building jupyterlab assets (production, minimized)
The extension "@mamba-org/gator-lab" is outdated.

The extension "@jupyterlab/git" is outdated.

The extension "nbdime-jupyterlab" is outdated.

An error occured.
ValueError: The extension "@bokeh/jupyter_bokeh" does not yet support the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab                        Extension      Package
>=3.0.4 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/application
>=3.0.3 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/apputils
>=3.0.4 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/notebook
>=3.0.3 <3.1.0                    >=2.0.1 <3.0.0 @jupyterlab/rendermime-interfaces
>=6.0.3 <6.1.0                    >=5.0.2 <6.0.0 @jupyterlab/services
See the log file for details:  /tmp/jupyterlab-debug-afcxq557.log
The command '/bin/sh -c jupyter labextension install @jupyter-widgets/jupyterlab-manager     && jupyter serverextension enable voila --sys-prefix     && jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-leaflet     && jupyter labextension install @bokeh/jupyter_bokeh     && jupyter labextension install @pyviz/jupyterlab_pyviz     && jupyter labextension install @jupyterlab/debugger     && jupyter labextension install @jupyterlab/google-drive     && jupyter labextension install jupyterlab-topbar-extension                                     jupyterlab-system-monitor                                     jupyterlab-topbar-text
              jupyterlab-logout                                     jupyterlab-theme-toggle                                     jupyterlab_conda' returned a non-zero code: 1
```