docker: py311-240813: initial jenkins build, default nb, 2 error, lots of output change
pavics-sdi-master/docs/source/notebooks/eccc-geoapi-xclim.ipynb
DeprecationWarning: ('Explicitly passing `grid_mapping` with DataArray
of geometries is deprecated. Please set a `grid_mapping` attribute on
`geometries`, ', 'and set the grid mapping variable as a coordinate')

PAVICS-landing-master/content/notebooks/climate_indicators/PAVICStutorial_ClimateDataAnalysis-4Ensembles.ipynb
AttributeError: module 'xclim.ensembles' has no attribute
'change_significance'

**DeprecationWarning**: ('Explicitly passing `grid_mapping` with DataArray of geometries is deprecated. Please set a `grid_mapping` attribute on `geometries`, ', 'and set the grid mapping variable as a coordinate')
```
15:07:48  ___ pavics-sdi-master/docs/source/notebooks/eccc-geoapi-xclim.ipynb::Cell 2 ____
15:07:48  Notebook cell execution failed
15:07:48  Cell 2: Cell execution caused an exception
15:07:48
15:07:48  Input:
15:07:48  # NBVAL_IGNORE_OUTPUT
15:07:48
15:07:48
15:07:48  # Convert the GeoDataFrame to an xarray.Dataset
15:07:48  # Different stations are aligned along the `station` dimension
15:07:48  ds = preprocessing(gdf)
15:07:48  ds
15:07:48
15:07:48  Traceback:
15:07:48
15:07:48  ---------------------------------------------------------------------------
15:07:48  DeprecationWarning                        Traceback (most recent call last)
15:07:48  Cell In[1], line 6
15:07:48        1 # NBVAL_IGNORE_OUTPUT
15:07:48        2
15:07:48        3
15:07:48        4 # Convert the GeoDataFrame to an xarray.Dataset
15:07:48        5 # Different stations are aligned along the `station` dimension
15:07:48  ----> 6 ds = preprocessing(gdf)
15:07:48        7 ds
15:07:48
15:07:48  Cell In[1], line 40, in preprocessing(gdf)
15:07:48       38 # Convert geometries to CF - creates a features dimension
15:07:48       39 ds = cfxr.geometry.reshape_unique_geometries(ds)
15:07:48  ---> 40 coords = cfxr.shapely_to_cf(ds.geometry, grid_mapping="longitude_latitude")
15:07:48       41 coords = coords.drop_vars(["geometry_container", "x", "y"])
15:07:48       42 ds = xr.merge([ds.drop_vars("geometry"), coords])
15:07:48
15:07:48  File /opt/conda/envs/birdy/lib/python3.11/site-packages/cf_xarray/geometry.py:456, in shapely_to_cf(geometries, grid_mapping, suffix)
15:07:48      423 """
15:07:48      424 Convert a DataArray with shapely geometry objects into a CF-compliant dataset.
15:07:48      425
15:07:48     (...)
15:07:48      452 Please refer to the CF conventions document: [http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#geometries](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#geometries%1B[39;00m)
15:07:48      453 """
15:07:48      455 if isinstance(geometries, xr.DataArray) and grid_mapping is not None:
15:07:48  --> 456     raise DeprecationWarning(
15:07:48      457         "Explicitly passing `grid_mapping` with DataArray of geometries is deprecated. "
15:07:48      458         "Please set a `grid_mapping` attribute on `geometries`, ",
15:07:48      459         "and set the grid mapping variable as a coordinate",
15:07:48      460     )
15:07:48      462 # Get all types to call the appropriate translation function.
15:07:48      463 types = {
15:07:48      464     geom.item().geom_type if isinstance(geom, xr.DataArray) else geom.geom_type
15:07:48      465     for geom in geometries
15:07:48      466 }
15:07:48
15:07:48  DeprecationWarning: ('Explicitly passing `grid_mapping` with DataArray of geometries is deprecated. Please set a `grid_mapping` attribute on `geometries`, ', 'and set the grid mapping variable as a coordinate')
```

**AttributeError**: module 'xclim.ensembles' has no attribute 'change_significance'
```
15:07:48  _ PAVICS-landing-master/content/notebooks/climate_indicators/PAVICStutorial_ClimateDataAnalysis-4Ensembles.ipynb::Cell 2 _
15:07:48  Notebook cell execution failed
15:07:48  Cell 2: Cell execution caused an exception
15:07:48
15:07:48  Input:
15:07:48  fut = ds_ens.sel(time=slice("2071", "2100")).chunk(dict(realization=-1))
15:07:48  ref = ds_ens.sel(time=slice("1981", "2010")).chunk(dict(realization=-1))
15:07:48
15:07:48  chng_f, pos_f = xens.change_significance(
15:07:48      fut.sel(time=fut["time.season"] == "JJA"),
15:07:48      ref.sel(time=ref["time.season"] == "JJA"),
15:07:48      test="ttest",
15:07:48  )
15:07:48  plt.figure(
15:07:48      figsize=(15, 6),
15:07:48  )
15:07:48
15:07:48  plt.subplot(1, 2, 1)
15:07:48  chng_f.tx_days_above_27.plot(cmap="RdBu_r", vmin=0, vmax=1)
15:07:48
15:07:48  t1 = plt.title(chng_f.description.split(".")[0])
15:07:48
15:07:48  plt.subplot(1, 2, 2)
15:07:48  pos_f.tx_days_above_27.plot(cmap="RdBu_r", vmin=0, vmax=1)
15:07:48  t1 = plt.title(
15:07:48      "Fraction of members with significant change that agree on positive change"
15:07:48  )
15:07:48
15:07:48  Traceback:
15:07:48
15:07:48  ---------------------------------------------------------------------------
15:07:48  AttributeError                            Traceback (most recent call last)
15:07:48  Cell In[1], line 4
15:07:48        1 fut = ds_ens.sel(time=slice("2071", "2100")).chunk(dict(realization=-1))
15:07:48        2 ref = ds_ens.sel(time=slice("1981", "2010")).chunk(dict(realization=-1))
15:07:48  ----> 4 chng_f, pos_f = xens.change_significance(
15:07:48        5     fut.sel(time=fut["time.season"] == "JJA"),
15:07:48        6     ref.sel(time=ref["time.season"] == "JJA"),
15:07:48        7     test="ttest",
15:07:48        8 )
15:07:48        9 plt.figure(
15:07:48       10     figsize=(15, 6),
15:07:48       11 )
15:07:48       13 plt.subplot(1, 2, 1)
15:07:48
15:07:48  AttributeError: module 'xclim.ensembles' has no attribute 'change_significance'
```

The rest of the errors are not code errors but output change so a simple refresh will be able to fix.