jenkins: allow to disable running stress-test.ipynb
It seems once the stress-test.ipynb starts failing, subsequent notebooks
are more likely to have the following errors:

```
  ServiceException: <?xml version="1.0" encoding="utf-8"?>
  <ExceptionReport version="1.0.0"
      xmlns="http://www.opengis.net/ows/1.1"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd">
      <Exception exceptionCode="NoApplicableCode" locator="AccessForbidden">
          <ExceptionText>Not authorized to access this resource. Missing user authentication.</ExceptionText>
      </Exception>
  </ExceptionReport>
```