docker: remove jupyterlab/google-drive since it still does not support jupyterlab v3
```
Step 11/20 : RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager     && jupyter serverextension enable voila --sys-prefix     && jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-leaflet     && jupyter labextension install @jupyterlab/debugger     && jupyter labextension install @jupyterlab/google-drive     && jupyter labextension install jupyterlab-topbar-text                                     jupyterlab_conda
 ---> Running in 96e4392006b2
Building jupyterlab assets (production, minimized)
Enabling: voila
- Writing config: /opt/conda/envs/birdy/etc/jupyter
    - Validating...
      voila 0.2.10 OK
Building jupyterlab assets (production, minimized)
Building jupyterlab assets (production, minimized)
\  An error occured.
ValueError: The extension "@jupyterlab/google-drive" does not yet support the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab                  Extension       Package
>=3.0.11 <3.1.0             >=2.0.0 <3.0.0  @jupyterlab/application
>=3.0.9 <3.1.0              >=2.0.0 <3.0.0  @jupyterlab/apputils
>=5.0.6 <5.1.0              >=4.0.0 <5.0.0  @jupyterlab/coreutils
>=3.0.11 <3.1.0             >=2.0.0 <3.0.0  @jupyterlab/docmanager
>=3.0.11 <3.1.0             >=2.0.0 <3.0.0  @jupyterlab/filebrowser
>=3.0.9 <3.1.0              >=2.0.0 <3.0.0  @jupyterlab/mainmenu
>=6.0.9 <6.1.0              >=5.0.0 <6.0.0  @jupyterlab/services
>=3.0.6 <3.1.0              >=2.0.0 <3.0.0  @jupyterlab/settingregistry
See the log file for details:  /tmp/jupyterlab-debug-shgkoz6v.log
The command '/bin/sh -c jupyter labextension install @jupyter-widgets/jupyterlab-manager     && jupyter serverextension enable voila --sys-prefix     && jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-leaflet     && jupyter labextension install @jupyterlab/debugger     && jupyter labextension install @jupyterlab/google-drive     && jupyter labextension install jupyterlab-topbar-text                                     jupyterlab_conda' returned a non-zero code: 1
```