docker: py311-241216: initial jenkins build, raven nb, several errors, same cause
ImportError: cannot import name 'readers' from 'intake' (/opt/conda/envs/birdy/lib/python3.11/site-packages/intake/__init__.py)

23:05:39  =========================== short test summary info ============================
23:05:39  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 2
23:05:39  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 3
23:05:39  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 4
23:05:39  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 5
23:05:39  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 6
23:05:39  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 7
23:05:39  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 8
23:05:39  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 9
23:05:39  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 10
23:05:39  FAILED RavenPy-master/docs/notebooks/08_Getting_and_bias_correcting_CMIP6_data.ipynb::Cell 10
23:05:39  FAILED RavenPy-master/docs/notebooks/08_Getting_and_bias_correcting_CMIP6_data.ipynb::Cell 11
23:05:39  FAILED RavenPy-master/docs/notebooks/08_Getting_and_bias_correcting_CMIP6_data.ipynb::Cell 12
23:05:39  FAILED RavenPy-master/docs/notebooks/08_Getting_and_bias_correcting_CMIP6_data.ipynb::Cell 13
23:05:39  FAILED RavenPy-master/docs/notebooks/08_Getting_and_bias_correcting_CMIP6_data.ipynb::Cell 14
23:05:39  FAILED RavenPy-master/docs/notebooks/08_Getting_and_bias_correcting_CMIP6_data.ipynb::Cell 15
23:05:39  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 10
23:05:39  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 13
23:05:39  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 14
23:05:39  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 15
23:05:39  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 16
23:05:39  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 17
23:05:39  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 18
23:05:39  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 19
23:05:39  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 20
23:05:39  ================== 28 failed, 214 passed in 582.63s (0:09:42) ==================