docker: pin rasterio to get latest ravenpy 0.7.5
Could not do a regular full clean build, some jupyter plugin failed to
build.  Had to do an "update" build.

```
Step 10/20 : RUN jupyter lab build
 ---> Running in e0e81f49ed16
[LabBuildApp] JupyterLab 3.2.5
[LabBuildApp] Building in /opt/conda/envs/birdy/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (production, minimized)
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (i.e., the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

An error occurred.
RuntimeError: npm dependencies failed to install
See the log file for details:  /tmp/jupyterlab-debug-7fnbmcy2.log
The command '/bin/sh -c jupyter lab build' returned a non-zero code: 1

[LabBuildApp] Building in /opt/conda/envs/birdy/share/jupyter/lab
[LabBuildApp] Node v15.14.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] > node /opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning @blueprintjs/core@3.52.0: Invalid bin entry for "upgrade-blueprint-2.0.0-rename" (in "@blueprintjs/core").
warning @blueprintjs/core@3.52.0: Invalid bin entry for "upgrade-blueprint-3.0.0-rename" (in "@blueprintjs/core").
error @npmcli/fs@1.1.0: The engine "node" is incompatible with this module. Expected version "^12.13.0 || ^14.15.0 || >=16". Got "15.14.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 48, in debug_logging
    yield

[LabBuildApp]   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/labapp.py", line 176, in start
    raise e

[LabBuildApp]   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/labapp.py", line 173, in start
    app_options=app_options, production = production, minimize=self.minimize)

[LabBuildApp]   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/commands.py", line 483, in build
    production=production, minimize=minimize, clean_staging=clean_staging)

[LabBuildApp]   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/commands.py", line 688, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

[LabBuildApp] Exiting application: JupyterLab
```

Update build logs:

```
Step 3/4 : RUN umask 0000     && conda install -c conda-forge -c cdat -c bokeh -c plotly -c defaults -n birdy "rasterio<=1.2.6" "ravenpy>=0.7.5"
 ---> Running in 4b4ac2aeb1cb
Collecting package metadata (current_repodata.json): ...working... WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.*, but conda is ignoring the .* and treating it as 3
done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working...      done

==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 4.11.0

Please update conda by running

    $ conda update -n base -c defaults conda

  environment location: /opt/conda/envs/birdy

  added / updated specs:
    - rasterio[version='<=1.2.6']
    - ravenpy[version='>=0.7.5']

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cartopy-0.20.0             |   py37hbe109c4_0         1.7 MB  conda-forge
    click-7.1.2                |     pyh9f0ad1d_0          64 KB  conda-forge
    gdal-3.3.2                 |   py37hd5a0ba4_2         1.6 MB  conda-forge
    geotiff-1.7.0              |       h4f31c25_0         295 KB  conda-forge
    libgdal-3.3.2              |       hd2dd7ad_2        13.1 MB  conda-forge
    libspatialite-5.0.1        |       h8694cbe_6         4.4 MB  conda-forge
    proj-8.0.1                 |       h277dcde_0         3.1 MB  conda-forge
    pyproj-3.2.1               |   py37h1939ec9_5         519 KB  conda-forge
    rasterio-1.2.6             |   py37hc20819c_2         8.3 MB  conda-forge
    ravenpy-0.7.5              |     pyhff6ddc9_0         5.9 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        38.9 MB

The following packages will be UPDATED:

  pyproj                               3.2.1-py37hd495510_2 --> 3.2.1-py37h1939ec9_5
  ravenpy                                0.7.2-pyhff6ddc9_0 --> 0.7.5-pyhff6ddc9_0

The following packages will be SUPERSEDED by a higher-priority channel:

  click              conda-forge/linux-64::click-8.0.3-py3~ --> conda-forge/noarch::click-7.1.2-pyh9f0ad1d_0

The following packages will be DOWNGRADED:

  cartopy                             0.20.1-py37h259df35_1 --> 0.20.0-py37hbe109c4_0
  gdal                                 3.3.3-py37h7b489ff_0 --> 3.3.2-py37hd5a0ba4_2
  geotiff                                  1.7.0-hcfb7246_3 --> 1.7.0-h4f31c25_0
  libgdal                                  3.3.3-h356f897_0 --> 3.3.2-hd2dd7ad_2
  libspatialite                            5.0.1-h8796b1e_9 --> 5.0.1-h8694cbe_6
  proj                                     8.1.1-h277dcde_2 --> 8.0.1-h277dcde_0
  rasterio                            1.2.10-py37hffcf04f_0 --> 1.2.6-py37hc20819c_2

Proceed ([y]/n)?

Downloading and Extracting Packages
rasterio-1.2.6       | 8.3 MB    | ########## | 100%
pyproj-3.2.1         | 519 KB    | ########## | 100%
libspatialite-5.0.1  | 4.4 MB    | ########## | 100%
cartopy-0.20.0       | 1.7 MB    | ########## | 100%
proj-8.0.1           | 3.1 MB    | ########## | 100%
ravenpy-0.7.5        | 5.9 MB    | ########## | 100%
gdal-3.3.2           | 1.6 MB    | ########## | 100%
click-7.1.2          | 64 KB     | ########## | 100%
geotiff-1.7.0        | 295 KB    | ########## | 100%
libgdal-3.3.2        | 13.1 MB   | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Removing intermediate container 4b4ac2aeb1cb
 ---> 1304fc9ef797
Step 4/4 : USER jenkins
 ---> Running in 98ce1503a604
Removing intermediate container 98ce1503a604
 ---> e875aa213e2f
Successfully built e875aa213e2f
```