docker: py311-241205: initial jenkins build, raven nb, many nb with apparently same root cause
  ValueError: config should be a symbolic configuration, where params are not set to their numerical values.

  HydroShare_integration is a known error, the rest are related to the error above.

  =========================== short test summary info ============================
  FAILED RavenPy-master/docs/notebooks/06_Raven_calibration.ipynb::Cell 3
  FAILED RavenPy-master/docs/notebooks/06_Raven_calibration.ipynb::Cell 4
  FAILED RavenPy-master/docs/notebooks/06_Raven_calibration.ipynb::Cell 5
  FAILED RavenPy-master/docs/notebooks/HydroShare_integration.ipynb::Cell 0
  FAILED RavenPy-master/docs/notebooks/HydroShare_integration.ipynb::Cell 1
  FAILED RavenPy-master/docs/notebooks/HydroShare_integration.ipynb::Cell 2
  FAILED RavenPy-master/docs/notebooks/HydroShare_integration.ipynb::Cell 3
  FAILED RavenPy-master/docs/notebooks/Perform_Regionalization.ipynb::Cell 2
  FAILED RavenPy-master/docs/notebooks/Perform_Regionalization.ipynb::Cell 3
  FAILED RavenPy-master/docs/notebooks/Perform_Regionalization.ipynb::Cell 4
  FAILED RavenPy-master/docs/notebooks/Perform_Regionalization.ipynb::Cell 5
  FAILED RavenPy-master/docs/notebooks/Perform_Regionalization.ipynb::Cell 6
  FAILED RavenPy-master/docs/notebooks/Running_HMETS_with_CANOPEX_dataset.ipynb::Cell 7
  FAILED RavenPy-master/docs/notebooks/Running_HMETS_with_CANOPEX_dataset.ipynb::Cell 8
  FAILED RavenPy-master/docs/notebooks/Running_HMETS_with_CANOPEX_dataset.ipynb::Cell 9
  FAILED RavenPy-master/docs/notebooks/Running_HMETS_with_CANOPEX_dataset.ipynb::Cell 10
  FAILED RavenPy-master/docs/notebooks/Running_HMETS_with_CANOPEX_dataset.ipynb::Cell 11
  FAILED RavenPy-master/docs/notebooks/Running_HMETS_with_CANOPEX_dataset.ipynb::Cell 12
  FAILED RavenPy-master/docs/notebooks/Running_HMETS_with_CANOPEX_dataset.ipynb::Cell 13
  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 16
  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 17
  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 18
  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 19
  FAILED RavenPy-master/docs/notebooks/paper/Perform_a_climate_change_impact_study_on_a_watershed.ipynb::Cell 20
  ================= 24 failed, 218 passed in 1026.33s (0:17:06) ==================

```
  _______ RavenPy-master/docs/notebooks/06_Raven_calibration.ipynb::Cell 3 _______
  Notebook cell execution failed
  Cell 3: Cell execution caused an exception

  Input:
  # In order to calibrate your model, you need to give the lower and higher bounds of the model. In this case, we are passing
  # the boundaries for a GR4JCN, but it's important to change them, if you are using another model. Note that the list of these
  # boundaries for each model is at the end of this notebook.
  low_params = (0.01, -15.0, 10.0, 0.0, 1.0, 0.0)
  high_params = (2.5, 10.0, 700.0, 7.0, 30.0, 1.0)

  spot_setup = SpotSetup(
      config=model_config,
      low=low_params,
      high=high_params,
  )

  Traceback:

  ---------------------------------------------------------------------------
  ValueError                                Traceback (most recent call last)
  Cell In[1], line 8
        4 low_params = (0.01, -15.0, 10.0, 0.0, 1.0, 0.0)
        5 high_params = (2.5, 10.0, 700.0, 7.0, 30.0, 1.0)
  ----> 8 spot_setup = SpotSetup(
        9     config=model_config,
       10     low=low_params,
       11     high=high_params,
       12 )

  File /opt/conda/envs/birdy/lib/python3.11/site-packages/ravenpy/utilities/calibration.py:38, in SpotSetup.__init__(self, config, low, high, workdir)
       24 """Class to configure spotpy with Raven emulators.
       25
       26 Parameters
     (...)
       35     Work directory. If None, a temporary directory will be created.
       36 """
       37 if not config.is_symbolic:
  ---> 38     raise ValueError(
       39         "config should be a symbolic configuration, where params are not set to their numerical "
       40         "values."
       41     )
       43 self.config = config
       44 self.path = Path(workdir or tempfile.mkdtemp())

  ValueError: config should be a symbolic configuration, where params are not set to their numerical values.
```