docker: add pytest-tornasync for notebooks tests
Fix following Jenkins notebook test error:

```
  + export PYTHONWARNINGS=ignore:Unverified HTTPS request
  + py.test --nbval notebooks/hummingbird.ipynb pavics-sdi-master/docs/source/notebooks/WCS_example.ipynb pavics-sdi-master/docs/source/notebooks/WFS_example.ipynb pavics-sdi-master/docs/source/notebooks/WMS_example.ipynb pavics-sdi-master/docs/source/notebooks/WPS_example.ipynb pavics-sdi-master/docs/source/notebooks/catalog_search.ipynb pavics-sdi-master/docs/source/notebooks/esgf-dap.ipynb pavics-sdi-master/docs/source/notebooks/opendap.ipynb pavics-sdi-master/docs/source/notebooks/pavics_thredds.ipynb pavics-sdi-master/docs/source/notebooks/rendering.ipynb pavics-sdi-master/docs/source/notebooks/subsetting.ipynb finch-master/docs/source/notebooks/dap_subset.ipynb finch-master/docs/source/notebooks/finch-usage.ipynb --sanitize-with notebooks/output-sanitize.cfg
  Traceback (most recent call last):
    File "/opt/conda/envs/birdy/lib/python3.7/site-packages/_pytest/config/__init__.py", line 689, in import_plugin
      __import__(importspec)
  ModuleNotFoundError: No module named 'pytest_tornasync'

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/opt/conda/envs/birdy/bin/py.test", line 11, in <module>
      sys.exit(main())
    File "/opt/conda/envs/birdy/lib/python3.7/site-packages/_pytest/config/__init__.py", line 136, in main
      config = _prepareconfig(args, plugins)
    File "/opt/conda/envs/birdy/lib/python3.7/site-packages/_pytest/config/__init__.py", line 314, in _prepareconfig
      pluginmanager=pluginmanager, args=args
    File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
      return self._hookexec(self, self.get_hookimpls(), kwargs)
    File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
      return self._inner_hookexec(hook, methods, kwargs)
    File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
      firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
    File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
      gen.send(outcome)
    File "/opt/conda/envs/birdy/lib/python3.7/site-packages/_pytest/helpconfig.py", line 99, in pytest_cmdline_parse
      config = outcome.get_result()  # type: Config
    File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
      raise ex[1].with_traceback(ex[2])
    File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
      res = hook_impl.function(*args)
    File "/opt/conda/envs/birdy/lib/python3.7/site-packages/_pytest/config/__init__.py", line 932, in pytest_cmdline_parse
      self.parse(args)
    File "/opt/conda/envs/birdy/lib/python3.7/site-packages/_pytest/config/__init__.py", line 1204, in parse
      self._preparse(args, addopts=addopts)
    File "/opt/conda/envs/birdy/lib/python3.7/site-packages/_pytest/config/__init__.py", line 1097, in _preparse
      self.pluginmanager.load_setuptools_entrypoints("pytest11")
    File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/manager.py", line 300, in load_setuptools_entrypoints
      self.register(plugin, name=ep.name)
    File "/opt/conda/envs/birdy/lib/python3.7/site-packages/_pytest/config/__init__.py", line 431, in register
      self.consider_module(plugin)
    File "/opt/conda/envs/birdy/lib/python3.7/site-packages/_pytest/config/__init__.py", line 656, in consider_module
      self._import_plugin_specs(getattr(mod, "pytest_plugins", []))
    File "/opt/conda/envs/birdy/lib/python3.7/site-packages/_pytest/config/__init__.py", line 663, in _import_plugin_specs
      self.import_plugin(import_spec)
    File "/opt/conda/envs/birdy/lib/python3.7/site-packages/_pytest/config/__init__.py", line 693, in import_plugin
      ).with_traceback(e.__traceback__) from e
    File "/opt/conda/envs/birdy/lib/python3.7/site-packages/_pytest/config/__init__.py", line 689, in import_plugin
      __import__(importspec)
  ImportError: Error importing plugin "pytest_tornasync": No module named 'pytest_tornasync'
  + EXIT_CODE=1
```