docker: set ESMFMKFILE env var for import xesmf since esmf-8.4.0
See https://github.com/conda-forge/esmf-feedstock/issues/91

Fix the following error:
```
  import xesmf as xe
  from xclim.subset import subset_bbox  # For subsetting
  from xclim.testing import open_dataset  # For opening xclim's
a

  #  A colormap with grey where the data is missing
  cmap = copy.copy(plt.cm.get_cmap("viridis"))
  cmap.set_bad("lightgray")

  Traceback:

-------------------------------------------------------------------
  KeyError                                  Traceback (most
all last)
  File
da/envs/birdy/lib/python3.8/site-packages/esmpy/interface/loadESMF.py:26
       25 try:
  ---> 26     esmfmk = os.environ["ESMFMKFILE"]
       27 except:

  File /opt/conda/envs/birdy/lib/python3.8/os.py:675, in
.__getitem__(self, key)
      673 except KeyError:
      674     # raise KeyError with the original key value
  --> 675     raise KeyError(key) from None
      676 return self.decodevalue(value)

  KeyError: 'ESMFMKFILE'
```