docker: add make to install ravenpy
```
/opt/conda/envs/birdy/lib/python3.7/site-packages/pip/_internal/commands/install.py:230: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/envs/birdy/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-869w0d42/ravenpy_a570cef4dabe4e5eaf58b51fcbfc51b3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-869w0d42/ravenpy_a570cef4dabe4e5eaf58b51fcbfc51b3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-i3ntgjje/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/envs/birdy/include/python3.7m/ravenpy --with-binaries
         cwd: /tmp/pip-install-869w0d42/ravenpy_a570cef4dabe4e5eaf58b51fcbfc51b3/
    Complete output (32 lines):
    running install
    Downloading raven source code..
    Extracting raven source code..
    Compiling raven..
    /bin/sh: 1: make: not found
    Command 'make ' returned non-zero exit status 127.
```